---
abstract: 'tokenize/hash large amount of strings efficiently'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  Data::Dumper: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0
  Test::Requires: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300012, CPAN::Meta::Converter version 2.120900'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-SpeedyFx
requires:
  Exporter: 0
  File::Slurp: 0
  Getopt::Long: 0
  List::MoreUtils: 0
  Pod::Usage: 0
  XSLoader: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/creaktive/Text-SpeedyFx/issues
  homepage: https://github.com/creaktive/Text-SpeedyFx
  repository: git://github.com/creaktive/Text-SpeedyFx.git
version: 0.003
